"""added location to stop table

Revision ID: 0421ebd86d68
Revises: 7898eb4faf18
Create Date: 2020-04-16 17:43:20.113219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0421ebd86d68'
down_revision = '7898eb4faf18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stops', sa.Column('location_city', sa.String(), nullable=True))
    op.add_column('stops', sa.Column('location_province', sa.String(), nullable=True))
    op.alter_column('stops', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stops', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('stops', 'location_province')
    op.drop_column('stops', 'location_city')
    # ### end Alembic commands ###
