"""added removed ondelete in association table

Revision ID: 064227a1e12a
Revises: 14b76ca20330
Create Date: 2020-05-17 14:54:13.348255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '064227a1e12a'
down_revision = '14b76ca20330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stop_line_association_line_id_fkey', 'stop_line_association', type_='foreignkey')
    op.drop_constraint('stop_line_association_stop_id_fkey', 'stop_line_association', type_='foreignkey')
    op.create_foreign_key(None, 'stop_line_association', 'stops', ['stop_id'], ['id'])
    op.create_foreign_key(None, 'stop_line_association', 'lines', ['line_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stop_line_association', type_='foreignkey')
    op.drop_constraint(None, 'stop_line_association', type_='foreignkey')
    op.create_foreign_key('stop_line_association_stop_id_fkey', 'stop_line_association', 'stops', ['stop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('stop_line_association_line_id_fkey', 'stop_line_association', 'lines', ['line_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
