"""added cascade ondelete to association table

Revision ID: 14b76ca20330
Revises: c0a59fbed4dc
Create Date: 2020-05-17 14:31:34.415828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14b76ca20330'
down_revision = 'c0a59fbed4dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stop_line_association_line_id_fkey', 'stop_line_association', type_='foreignkey')
    op.drop_constraint('stop_line_association_stop_id_fkey', 'stop_line_association', type_='foreignkey')
    op.create_foreign_key(None, 'stop_line_association', 'stops', ['stop_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'stop_line_association', 'lines', ['line_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stop_line_association', type_='foreignkey')
    op.drop_constraint(None, 'stop_line_association', type_='foreignkey')
    op.create_foreign_key('stop_line_association_stop_id_fkey', 'stop_line_association', 'stops', ['stop_id'], ['id'])
    op.create_foreign_key('stop_line_association_line_id_fkey', 'stop_line_association', 'lines', ['line_id'], ['id'])
    # ### end Alembic commands ###
