"""changed location_city -> location

Revision ID: 969c7d0201e6
Revises: a8d507906ac9
Create Date: 2020-04-16 17:48:54.390267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969c7d0201e6'
down_revision = 'a8d507906ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stops', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('stops', 'location_city')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stops', sa.Column('location_city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('stops', 'location')
    # ### end Alembic commands ###
