"""added stoptypes to lines

Revision ID: ab3a72b0d44e
Revises: 571809b24b05
Create Date: 2020-05-11 14:18:08.161689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab3a72b0d44e'
down_revision = '571809b24b05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('stoptypes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lines', 'stoptypes')
    # ### end Alembic commands ###
