"""added railway class

Revision ID: 12e094c7d1ed
Revises: f8ffcd2b43a4
Create Date: 2020-05-10 22:13:34.334768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12e094c7d1ed'
down_revision = 'f8ffcd2b43a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('short_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('lines', sa.Column('railway_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lines', 'railways', ['railway_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lines', type_='foreignkey')
    op.drop_column('lines', 'railway_id')
    op.drop_table('railways')
    # ### end Alembic commands ###
