"""removed railways class

Revision ID: 571809b24b05
Revises: b4596b4f54c6
Create Date: 2020-05-10 22:28:49.644518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571809b24b05'
down_revision = 'b4596b4f54c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('railways')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('railways',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('short_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='railways_pkey')
    )
    # ### end Alembic commands ###
