"""added stopnumber_prefix to line

Revision ID: 9b693009efb7
Revises: beef422a19bc
Create Date: 2020-05-13 17:44:13.255338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b693009efb7'
down_revision = 'beef422a19bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('stopnumber_prefix', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lines', 'stopnumber_prefix')
    # ### end Alembic commands ###
