"""removed railways lines constraints

Revision ID: b4596b4f54c6
Revises: a721a707754b
Create Date: 2020-05-10 22:27:28.475099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4596b4f54c6'
down_revision = 'a721a707754b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('lines_railway_id_fkey', 'lines', type_='foreignkey')
    op.drop_column('lines', 'railway_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('railway_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('lines_railway_id_fkey', 'lines', 'railways', ['railway_id'], ['id'])
    # ### end Alembic commands ###
