"""cascade

Revision ID: b690f1a52df7
Revises: dc0e2f11c0f6
Create Date: 2020-05-16 16:49:17.679792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b690f1a52df7'
down_revision = 'dc0e2f11c0f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('stop_line_association_stop_id_fkey', 'stop_line_association', type_='foreignkey')
    op.drop_constraint('stop_line_association_line_id_fkey', 'stop_line_association', type_='foreignkey')
    op.create_foreign_key(None, 'stop_line_association', 'lines', ['line_id'], ['id'], ondelete='cascade')
    op.create_foreign_key(None, 'stop_line_association', 'stops', ['stop_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stop_line_association', type_='foreignkey')
    op.drop_constraint(None, 'stop_line_association', type_='foreignkey')
    op.create_foreign_key('stop_line_association_line_id_fkey', 'stop_line_association', 'lines', ['line_id'], ['id'])
    op.create_foreign_key('stop_line_association_stop_id_fkey', 'stop_line_association', 'stops', ['stop_id'], ['id'])
    # ### end Alembic commands ###
