"""added stops_order to lines

Revision ID: c0a59fbed4dc
Revises: dfd07b9b42a3
Create Date: 2020-05-16 23:38:42.768224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a59fbed4dc'
down_revision = 'dfd07b9b42a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('stops_order', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lines', 'stops_order')
    # ### end Alembic commands ###
