"""added unique constraint to stop_line table

Revision ID: dc0e2f11c0f6
Revises: 9b693009efb7
Create Date: 2020-05-15 11:56:11.452615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0e2f11c0f6'
down_revision = '9b693009efb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('UC_stop_id_line_id', 'stop_line_association', ['stop_id', 'line_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('UC_stop_id_line_id', 'stop_line_association', type_='unique')
    # ### end Alembic commands ###
